apiVersion: v1
kind: Service
metadata:
  name: upload-service
  namespace: ai-demo
spec:
  selector:
    app: upload-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000
---
apiVersion: v1
kind: Pod
metadata:
  name: upload-service
  namespace: ai-demo
  labels:
    app: upload-service
spec:
  containers:
    - name: upload-service
      image: docker.io/aliok/upload-service:latest
      imagePullPolicy: Always
      ports:
        - containerPort: 5000
      env:
        - name: S3_ENDPOINT_URL
          value: https://minio.minio-operator.svc.cluster.local
        - name: S3_ACCESS_KEY_ID
          value: minio
        - name: S3_ACCESS_KEY_SECRET
          value: minio1234
        - name: S3_ACCESS_SSL_VERIFY
          value: "false"
        - name: S3_BUCKET_NAME
          value: ai-demo
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: upload-service
  namespace: ai-demo
spec:
  to:
    kind: Service
    name: upload-service
  port:
    targetPort: 5000
  tls:
    termination: edge
    insecureEdgeTerminationPolicy: None
  wildcardPolicy: None
