apiVersion: v1
kind: Secret
metadata:
  name: storage-configuration
  namespace: minio-operator
type: Opaque
stringData:
  config.env: |-
    export MINIO_ROOT_USER="minio"
    export MINIO_ROOT_PASSWORD="minio1234"
    export MINIO_STORAGE_CLASS_STANDARD="EC:0"
    export MINIO_BROWSER="on"
    export MINIO_NOTIFY_WEBHOOK_ENABLE_PRIMARY="on"
    export MINIO_NOTIFY_WEBHOOK_ENDPOINT_PRIMARY="http://event-display.ai-demo.svc.cluster.local:80"
