apiVersion: install.istio.io/v1beta1
kind: IstioOperator
spec:
  values:
    global:
      proxy:
        autoInject: disabled
      useMCP: false

  meshConfig:
    accessLogFile: /dev/stdout

  components:
    ingressGateways:
      - name: istio-ingressgateway
        enabled: true
        k8s:
          podAnnotations:
            cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
          service:
            type: NodePort
            ports:
            - name: status-port
              nodePort: 32599
              port: 15021
              protocol: TCP
              targetPort: 15021
            - name: http2
              nodePort: 30106
              port: 80
              protocol: TCP
              targetPort: 8080
            - name: https
              nodePort: 30233
              port: 443
              protocol: TCP
              targetPort: 8443

    pilot:
      enabled: true
      k8s:
        resources:
          requests:
            cpu: 200m
            memory: 200Mi
        podAnnotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "true"
        env:
          - name: PILOT_ENABLE_CONFIG_DISTRIBUTION_TRACKING
            value: "false"
