
---
apiVersion: v1
kind: Service
metadata:
  name: event-display
  namespace: ai-demo
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: event-display
  namespace: ai-demo
  labels:
    app: event-display
spec:
  containers:
    - name: event-display
      image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
      imagePullPolicy: Always
      ports:
        - containerPort: 8080

      env:
        - name: REQUEST_LOGGING_ENABLED
          value: "true"
---
apiVersion: eventing.knative.dev/v1
kind: Trigger
metadata:
  name: broker-event-display
  namespace: ai-demo
spec:
  broker: predictions-broker
  subscriber:
    ref:
      apiVersion: v1
      kind: Service
      name: broker-event-display
---
apiVersion: v1
kind: Service
metadata:
  name: broker-event-display
  namespace: ai-demo
spec:
  selector:
    app: broker-event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: broker-event-display
  namespace: ai-demo
  labels:
    app: broker-event-display
spec:
  containers:
    - name: event-display
      image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
      imagePullPolicy: Always
      ports:
        - containerPort: 8080

      env:
        - name: REQUEST_LOGGING_ENABLED
          value: "true"
