apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: minio-webhook-source
  namespace: ai-demo
  labels:
    app: minio-webhook-source
spec:
  template:
    spec:
      containers:
        - image: quay.io/pierdipi/minio-webhook-source:v1
          ports:
            - containerPort: 5000
          env:
            - name: POD_NAME
              value: "minio-webhook-source"
            - name: POD_NAMESPACE
              value: "ai-demo"
---
apiVersion: sources.knative.dev/v1
kind: SinkBinding
metadata:
  name: minio-webhook-source
  namespace: ai-demo
spec:
  subject:
    apiVersion: serving.knative.dev/v1
    kind: Service
    selector:
      matchLabels:
        app: minio-webhook-source
  sink:
    ref:
      apiVersion: eventing.knative.dev/v1
      kind: Broker
      name: predictions-broker