apiVersion: v1
kind: Service
metadata:
  name: event-display
  namespace: ai-demo
spec:
  selector:
    app: event-display
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: Pod
metadata:
  name: event-display
  namespace: ai-demo
  labels:
    app: event-display
spec:
  containers:
    - name: event-display
      image: gcr.io/knative-releases/knative.dev/eventing/cmd/event_display
      imagePullPolicy: Always
      ports:
        - containerPort: 8080

      env:
        - name: REQUEST_LOGGING_ENABLED
          value: "true"
