apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraPortMappings:
      # Istio ingress gateway port
      - containerPort: 30106
        hostPort: 80
      # Istio ingress gateway port
      - containerPort: 30233
        hostPort: 443
      # Ceph dashboard
      - containerPort: 30107
        hostPort: 30107
